### ISSUE TITLE
Player grabbed from behind door before "ghost-like" triggered

### ISSUE THREAD

**Issue by fstrike7** [dysphie/nmrih-door-protect#1]
Tested in nmo_in_the_darkv2
Door was jammed twice and still solid when zombie grabbed him

**Comment by dysphie** [comment]
This might be a bug with Sourcemod 1.11.6825 or lower. (https://github.com/alliedmodders/sourcemod/issues/1650)
Ensure you are running Sourcemod 1.11.6826 or higher and let me know if the problem still persists.

**Comment by fstrike7** [comment]
Seems map's issue, tested on Sourcemod 1.11.6826 with and without plugin happened twice.
